### ISSUE TITLE
8.4 is missing

### ISSUE THREAD

**Issue by L3o-pold** [containerbase/composer-prebuild#235]
PHP 8.4.1 tag / release is missing weeks after release / merge

**Comment by L3o-pold** [comment]
fixed: https://github.com/containerbase/composer-prebuild/releases/tag/2.8.4

**Comment by viceice** [comment]
you opened the issue right after the new composer version was released. you can't expect it to be released at the same time here. if needs at least a couple of hours until renovate processed it.

**Comment by viceice** [comment]
please update the issue description, it's wrong. you're referring to php, but this repo releases composer.
